### ISSUE TITLE
Squids seem unable to spawn.

### ISSUE THREAD

**Issue by TeetoKaziim** [Matryoshika/Underworld#18]
Seems like the issue is that squids want to spawn lower than sea level, but at y = 46 or higher. Sea level seems to be 32, meaning there are no Y values that fullfill both conditions.

**Comment by Matryoshika** [comment]
There is a small issue with Squids in 1.10, where they can spawn in any liquid, even "moving" aka "non-source-block", like flowing lava. You can use that to manually bypass this ;)

Added a clause in Underworld's mob-spawn mechanics however, to not ignore EntityAnimals OR EntityWaterMob, which squids extend. Should allow them to spawn, but will see if I'll need to add some restrictions to the Water-entities later on. Experience has taught me that squids love to spawn way too much. Hopefully the general restriction will keep them down, but hopefully not too much, and hopefully again, without them bottle-necking the spawning process, keeping other mobs from spawning (only x mobs can be in an area. If more than x are in that area, the spawning-mechanics stop, until x is lower than the limit)

**Comment by Matryoshika** [comment]
Life finally got around to giving me a break, so I'm finally able to upload the damned fixes.

Squids should be spawning more *often* now. 
If none spawns, try and kill some mobs nearby. The custom system for mob-spawns in Underworld has a built-in limit for entities in a certain area (as of now 16 mobs in a 64x 64z 128y area (still pretty common compared to vanilla if you calculate)) and will likely be moved to a config option in the near future.
(This is due to my optimizational nature, partly caused by my extended time as an admin for 30-40 servers in a single network for more than 2 years now)

Relevant code: https://github.com/Matryoshika/Underworld/commit/885d1207e0e62ddeb7dec8964b7b8609c0e8721b
