### ISSUE TITLE
World Type Override?

### ISSUE THREAD

**Issue by Cazadorsniper** [Matryoshika/Underworld#9]
Is it possible to add a config that allows this world type to override the default overworld world type (so people will have to be in that dimension no matter what)?

As a side note the lantern doesn't have a recipe (JEI not showing one), and the lantern causes a bit of lag while moving (probably from light updates).

**Comment by Matryoshika** [comment]
Damn it, the booleans got inverted for the recipes in the latest update. Already fixed for the next update.
Forcing default... hmmm. Going to have to take a look at that. The code is specifically made to be for the "Underworld" world type. Might require some re-structuring for that.

The Lantern, causes some FPS drops, yes. This is sadly due to how Minecraft works. I have tried to optimize it as much as possible, but bar doing what AtomicStryker (author of DynamicLights) does with core-modding and diverting calls that should go to vanilla methods, to his own methods, there's not much I can do.

**Comment by Cazadorsniper** [comment]
Ah I see, ok.

**Comment by Matryoshika** [comment]
I believe I have managed to do as requested :)
However, I can not in any way shape or form, promise that forcing the Underworld generation to any non-Underworld WorldTypes will be a smooth ride. Talking about mods with heavy worldgen like Underworld. Ores, etc should be fine. The heavier stuff; that might clash.

Btw: Love Po2 Titan. Wee bit easy though ;)

**Comment by Cazadorsniper** [comment]
thanks :D

and Kappa mode is still be worked on :P

**Comment by Matryoshika** [comment]
Underworld 0.1.12 is now available at CurseForge.
Closing issue as successfully completed.
